#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Sep 29 22:30:06 2019

@author: manimahesh
"""

import numpy as np
import pandas as pd
import os
import seaborn as sns
import matplotlib.pyplot as plt
os.chdir('Documents/Pandas')
ppl_data = pd.read_csv('People Charm case.csv')
ppl_data.isnull().sum()
sns.boxplot(y='lastEvaluation',data = ppl_data )
pd.crosstab(index = ppl_data['dept'],columns = ppl_data['salary'],margins = True,normalize = 'index')
sns.boxplot(y = 'numberOfProjects', data = ppl_data)
from sklearn.model_selection import train_test_split 
# for logistic regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
new_data = pd.get_dummies(ppl_data, drop_first = True)
columns_list = list(new_data.columns)
#features = columns_list
del columns_list[6]
features = columns_list
print(features)
y = new_data['left'].values
print(y)

x = new_data[features].values
print(x)
#train_x,test_x,train_y,test_y = train_test_split(x,y,test_size = 0.75, random_state = 2)
#logistic = LogisticRegression()

#logistic.fit(train_x,train_y)
#prediction = logistic.predict(test_x)
#confusion_matrix = confusion_matrix(test_y, prediction)
#print(confusion_matrix)

#accuracy_score = accuracy_score(test_y, prediction)
#print(accuracy_score)

plt.hist(new_data['avgMonthlyHours'])


from sklearn.neighbors import KNeighborsClassifier
#import matplotlib.pyplot as plt
train_x,test_x,train_y,test_y = train_test_split(x,y,test_size = 0.75, random_state = 0)

KNN_classifier = KNeighborsClassifier(n_neighbors = 2)
KNN_classifier.fit(train_x,train_y)
prediction = KNN_classifier.predict(test_x)
confusion_matrix = confusion_matrix(test_y, prediction)
print(confusion_matrix)
accuracy_score = accuracy_score(test_y,prediction)
print(accuracy_score)

sns.boxplot(y= 'lastEvaluation', x = 'numberOfProjects', data = new_data)
